### ISSUE TITLE
Error 403 when testing GM API

### ISSUE THREAD

**Issue by seorsum1** [metheos/node-oauth2-gm#1]
I cloned your repo and updated all the dependencies, input my information to .env and get this error when trying 'npm start':

token_type: 'bearer',
  issued_token_type: 'urn:ietf:params:oauth:token-type:access_token',
  expires_in: '1799',
  scope: 'gmoc priv user_trailer user role_owner onstar',
  onstar_account_info: { account_no: '#######', country_code: 'US' },
  errors: null,
  expires_at: 1733097317
}
Testing GM API Request
GM API Request Error 403
Error details: { error: { code: '403', description: 'Authorization failed' } }
API Test failed: Forbidden

**Comment by metheos** [comment]
It looks like your access  token was created successfully. That's the main purpose of this repository.
The test GM API Request should only fail at that point if the VIN provided in .env was invalid.

**Comment by seorsum1** [comment]
I mistyped my VIN, am an idiot, thanks!

**Comment by metheos** [comment]
Ok Cool, glad it's working!
